# Generated by Django 5.1.7 on 2025-04-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_cartorder_product_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="mobile",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
