# Generated by Django 5.1.7 on 2025-04-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cleaned_ingredients', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField()),
                ('image_name', models.CharField(help_text="Just the image file name without extension, e.g., 'my-recipe-image'", max_length=255)),
                ('original_index', models.IntegerField(db_index=True, help_text='Original row index from the CSV file', unique=True)),
            ],
        ),
    ]
