# Generated by Django 5.1.7 on 2025-05-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Analytics',
                'ordering': ['-date_created'],
            },
        ),
    ]
